### ISSUE TITLE
custom location?

### ISSUE THREAD

**Issue by ghimireprashant** [Abedalkareem/MaterialTapTargetPrompt-iOS#1]
is it possible for custom location?
now it only show either left or right.

**Comment by Abedalkareem** [comment]
for now no , I'm going to add this in future .

**Comment by Abedalkareem** [comment]
I added new positions topLeft, topRight, centerLeft, centerRight, cenertTop, centerBottom

**Comment by keldii** [comment]
Hi Abdelkarrem,
Is it possible to put the textPosition at centerTop ? When I tried to use "cenertTop" that reacts like centerBottom. So the text goes out of the screen.

**Comment by keldii** [comment]
Thanks :-)

**Comment by keldii** [comment]
I tried to figure out why this issue and I think the problem come from the file MaterialTapTargetPrompt.swift from line 111 to 116. You have the same value for centerBottom and "cenertTop". 
I hope that is going to help you for fixing that. 
![Capture d’écran 2019-04-16 à 15 18 23](https://user-images.githubusercontent.com/45067986/56213017-84ee2200-605b-11e9-8a22-95d26357dfba.png)

**Comment by Abedalkareem** [comment]
Hi,

Thank you for reporting the issue!

I fixed the issue, can you try to update the pod again? (version 1.0.4)

Thank you.

**Comment by keldii** [comment]
Thanks you very much, that fixed that. 
Now I have another problem, our project supports SWIFT 4.2, and you made the SWIFT 5 version this morning. 
I have to find out an other solution because I'm not the one who can decide to change the project's Swift version.  And it's not planned for the moment.

**Comment by keldii** [comment]
Hi Abedalkareem,
I'm sorry to ask you this, but would it be possible for you to provide the last version with this issue fixed?
Thank you.

**Comment by Abedalkareem** [comment]
Hi Keldii,

I fixed the issue and uploaded new 4.2 swift version,

    pod 'MaterialTapTargetPrompt-iOS', '0.4.2'

Thank you!

**Comment by keldii** [comment]
THANK YOU VERY VERY MUCH !!!!
