### ISSUE TITLE
Action / Dismiss closure not invoked on tapping outside of the bubble view in release build

### ISSUE THREAD

**Issue by pratikkhobare** [Abedalkareem/MaterialTapTargetPrompt-iOS#11]
Hello,

I recently used this library to highlight 2 views in an application. First view is a imageView and on dismissing it the completion calls a function to invoke the bubble view for another view to be highlighted.

This is working completely fine in simulator and on iPhone device in debug mode but not working in a real device.

On release build, I am facing an issue where the bubble view is dismissed on tapping outside the bubble but the completion (action & dismissed closures) are not called. Because of this the next bubble view is not showing when tapped outside the bubble view for first bubble.

Could you please help resolving this issue?

Environment details:
Device - iPhone 12 mini, iPhone 12 pro max
OS - iOS 15.4.1

Thank you

**Comment by pratikkhobare** [comment]
Seems like the dismiss method invoked from the tap gesture of dummy view (when tapped outside the coloured circle) send the 'isButtonClicked' parameter as true, because of which the 'dismissed' closure is not invoked.

**Comment by Abedalkareem** [comment]
Hi!

You should listen for `action` and `dismissed`, action will be called when the button pressed and dismissed when any other place clicked.
