### ISSUE TITLE
Not able to dismiss tap target prompt from another View controller

### ISSUE THREAD

**Issue by ManishaQw** [Abedalkareem/MaterialTapTargetPrompt-iOS#4]
When app launches I have to show prompt but when app goes in background then open it and showing another View controller(where we are not using prompt) by notification not able to dismiss prompt.
Or any possibility we can dismiss prompt from AppDelegate.

**Comment by Abedalkareem** [comment]
Hello Manisha,
MaterialTapTargetPrompt  is a normal UIView so you can take an instance from the MaterialTapTargetPrompt, and then by using NotificationCenter you can remove it using `removeFromSuperView` method
