### ISSUE TITLE
Animation is doing at wrong place in iPhone 6s 

### ISSUE THREAD

**Issue by arishanapalli** [Abedalkareem/MaterialTapTargetPrompt-iOS#5]
I have used this design in my project but on initial load the screen the animation is doing worng place not on provided target-> animationButton

When I slide screen and release the animation is bring back the perfect position.

Please have a look for the iOS with your team.       

 tapTargetPrompt = MaterialTapTargetPrompt(controller: self, target: animationButton)
        tapTargetPrompt.circleColor = UIColor(
            red: 45.0/255,
            green: 35.0/255,
            blue: 25.0/255,
            alpha: 1.0);
        
        tapTargetPrompt.primaryText = "Shop Art"
        tapTargetPrompt.secondaryText = "Here you can shop for your need's"
        tapTargetPrompt.versionNumber =  "("+AppDelegate .versionBuild()+")";
        tapTargetPrompt.textPostion = .topRight

Thanks & Regards
A Kiran Kumar

**Comment by Abedalkareem** [comment]
Hello Kiran, 
Sorry for the delay in replying to you, can you please provide a screenshot?
and in which method you are adding it? viewDidLoad or viewDidApper ?

Thank you.

**Comment by arishanapalli** [comment]
Hi
Abedalkareem,

You need not to be say sorry!  
Your response really very fast!

I added it in viewWillAppear.

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.title = "About Us";
        self.loadAboutUsText();
    }

First screen is errorScreen, second one is expecting screen.
Button was added via storyboard.

![errorresult](https://user-images.githubusercontent.com/3903433/37251383-292394f8-2535-11e8-9c55-1bffe9736be0.jpeg)
![expectedresult](https://user-images.githubusercontent.com/3903433/37251384-29576c1a-2535-11e8-94a6-cb5be680ef79.jpeg)
![storyboard](https://user-images.githubusercontent.com/3903433/37251385-29821dac-2535-11e8-8e23-56b893111593.jpeg)

**Comment by Abedalkareem** [comment]
Can you show me the button you are trying to add the material tap target prompt around it, and is it a subview in other view/ views?

**Comment by arishanapalli** [comment]
I updated! please check it!  let me know if any further things needed, if I failed to understand what you needed.

**Comment by arishanapalli** [comment]
@Abedalkareem & Team,

Is my provided inputs is good enough, for understanding the issue?

**Comment by Abedalkareem** [comment]
Hello A Kiran Kumar.
Sorry for being late, I tried to find the problem you are facing but without any luck,  i tried the same thing you are doing and it works fine, please see the gif below.

![untitled](https://user-images.githubusercontent.com/14274852/38160809-2eeb98c8-34d4-11e8-9f66-ae8dd12cdece.gif)

I have updated the repo with this example I shown in the gif, try to do the same, and if it's still not working if you can answer those questions :
1- How do you open the view controller? push or modally?
2- Is this button inside another views? (if you can show the hierarchy of the view controller)
3- You are showing the view controller through code or storyboard? (can you show me the code for showing the view controller if from code, and if from storyboard can you show me the previous view controllers?)

Thank you.

**Comment by arishanapalli** [comment]
Hi
Abedalkareem,

Let me put more precisely for the following questions

1- How do you open the view controller? push or modally?
Ans: Hi open view controller  with push! (Added info Its loading from
Objective-C controller class into Swift Class)
Since I make a bridge to swift.

2- Is this button inside another views? (if you can show the hierarchy of
the view controller)

Ans: After drag and drop UIViewcontroller into storyboard I just drag the
UIButton to bottom left side.

So - UIViewcontroller.UIview.UIButton the default one.


3- You are showing the view controller through code or storyboard? (can you
show me the code for showing the view controller if from code, and if from
storyboard can you show me the previous view controllers?)

I am loading the UIViewController  with code.

Below code:

    SAAboutViewController *saAboutViewController = [storyboard
instantiateViewControllerWithIdentifier:@"SAAboutViewController"];

   [self.navigationController pushViewController:saAboutViewController
animated:YES];


Its loading with coding, and also for the first question its show
pushViewController.



*Let me know if still need any inputs from my end, I love to give it.*

*Because I like that effect a lot for my aboutus screen in my application.*




Regards

A Kiran Kumar

**Comment by Abedalkareem** [comment]
Did you try to do as the updated example in the repo?
Please if you can download the updated file from the library and put the code in view did appear.
I'm sorry but I failed to find the issue. can you also share the code you have for the MaterialTapTargetPrompt?

**Comment by arishanapalli** [comment]
Hi
Abedalkareem,

Its now work perfect! :-)
But,  I am bring another issues,
From your code I have removed the UINavigationController for
NextViewController
From ViewController Next button I drag to NextViewController and given show
navigation.
So, its show default back button to nextViewController.

Issues is I Need to click twice to go back previous view controller.
for first click its stop animation on second click it go back to preview
controller.

No I observer new one sorry for bring trouble part!

Regards
A Kiran Kumar

**Comment by arishanapalli** [comment]
Hi
Abedalkareem

Good news is the old code is also working perfectly now.

Now again I went back to old code MaterialTapTargetPrompt!

And added this method:


    override func viewDidAppear(_ animated: Bool) {

        super.viewWillAppear(animated)

        self.loadAboutUsText();

    }


Its working perfectly now.




Cheers!

**Comment by Abedalkareem** [comment]
Good !!
Thank you. !

**Comment by arishanapalli** [comment]
Sorry 
For troubling you! 

Cheers
