### ISSUE TITLE
Tap target circle position not set properly

### ISSUE THREAD

**Issue by GowthamanNdot** [Abedalkareem/MaterialTapTargetPrompt-iOS#6]

**Comment by Abedalkareem** [comment]
Hello, 
Can you provide a screenshot or video?

Thank you.

**Comment by GowthamanNdot** [comment]
Hi Abedalkareem,

Thanks for your reply. I have got the solution from git issues section and
the issue has been resolved.
Material Tap Target prompt is a nice one.

*Regards,*

P.Gowthaman - iOS Developer



*NDOT Inc / NDOT Technologies P.Ltd*
Module No 405,
Elcot SEZ, Tidel Park,
Coimbatore - 641 014, INDIA.
M: +91-73737-91414
www.ndot.in

*Mobility Company - Transportation 2.0*

**Comment by Abedalkareem** [comment]
Welcome and thank you for using it !.
