### ISSUE TITLE
Target misplaced for navigation item

### ISSUE THREAD

**Issue by duke1712** [Abedalkareem/MaterialTapTargetPrompt-iOS#7]
Hello In am facing issues in implementing the target on a navigation item. I have 2 icons in the left side of the navigation bar, but the target is pointing towards the top corner.

**Comment by Abedalkareem** [comment]
Hello
Can you share a screenshot?

**Comment by duke1712** [comment]
There are 2 items in the top left navigation item. I want to target to be on the second item.
![simulator screen shot - iphone se - 2018-08-12 at 00 00 39](https://user-images.githubusercontent.com/19251399/43996803-d018a05e-9dc2-11e8-9c8e-c568d1898909.png)

**Comment by Abedalkareem** [comment]
Can you please share the way that you are adding the button bar?
cuz I tried it now it works fine 

<img width="201" alt="screen shot 2018-08-12 at 10 53 35 am" src="https://user-images.githubusercontent.com/14274852/43999476-fc169a3e-9e1d-11e8-8215-7534bf14c1c6.png">

**Comment by duke1712** [comment]
```
 let nearbyButton = UIButton(type: .custom)
        nearbyButton.setImage(UIImage(named: "btn_map"), for: .normal)
        nearbyButton.frame = CGRect(x: 0, y: 0, width: 50, height: 50)
        nearbyButton.addTarget(self, action: #selector(ExploreViewController.doClickOnNearbyButton), for: .touchUpInside)
        
        let item1 = UIBarButtonItem(customView: nearbyButton)
        self.navigationItem.leftBarButtonItems?.append(item1)
        
        let tapTargetPrompt = MaterialTapTargetPrompt(target: item1) 
```
I have added the item1 as the target.
I even tried adding nearbyButton as the target but it didn't work

**Comment by Abedalkareem** [comment]
This code in the viewDidLoad or ViewDidApper?

**Comment by duke1712** [comment]
Its in viewDidAppear

**Comment by duke1712** [comment]
Ok I moved the code to viewDidLoad and its fixed. Thank you
